# ----------- Build stage -----------
FROM gradle:8-jdk21-alpine AS builder

WORKDIR /app

# 1. Копируем только файлы зависимостей и wrapper для кеша Gradle
COPY build.gradle settings.gradle gradle /app/
COPY apps/trackme-gateway/build.gradle /app/apps/trackme-gateway/

# 2. Прогреваем зависимости (кеширует максимально)
RUN --mount=type=cache,target=/root/.gradle,id=gradle-cache-gateway-deps gradle :trackme-gateway:dependencies --no-daemon

# 3. Копируем исходники только нужного приложения и его зависимости
COPY platform /app/platform
COPY apps/trackme-gateway /app/apps/trackme-gateway

# 4. Сборка JAR (кешируется благодаря шагам выше)
RUN --mount=type=cache,target=/root/.gradle,id=gradle-cache-gateway-clean gradle :trackme-gateway:clean :trackme-gateway:bootJar --no-daemon

# ----------- Runtime stage -----------
FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

# Не-root пользователь и curl (в 1 слой)
RUN addgroup -S appgroup && adduser -S appuser -G appgroup && apk add --no-cache curl
USER appuser

COPY --from=builder /app/apps/trackme-gateway/build/libs/trackme-gateway-*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]