plugins {
    id 'java'
    id 'org.springframework.boot'
    id 'jacoco'
    id 'com.github.node-gradle.node' version '7.0.2'
    id 'io.freefair.lombok'
    id "org.sonarqube" version "7.2.3.7755"
}

version = '1.0.0'

dependencies {
    implementation platform(project(':platform'))

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-authorization-server'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.liquibase:liquibase-core'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.session:spring-session-jdbc'
    implementation 'org.springframework.session:spring-session-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:postgresql'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.mapstruct:mapstruct'
    implementation 'org.springframework.kafka:spring-kafka'

    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.2'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
    testImplementation 'org.springframework.security:spring-security-test'


    developmentOnly 'org.springframework.boot:spring-boot-devtools:3.5.0'
    developmentOnly 'org.springframework.boot:spring-boot-docker-compose:3.5.0'
    runtimeOnly 'org.postgresql:postgresql'

    implementation project(':commons')
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
        resources {
            srcDirs = ['src/main/resources', 'database', 'frontend']
        }
    }
}

springBoot {
    buildInfo()
}

sonar {
    properties {
        property "sonar.language", "java"
        property "sonar.projectKey", "trackme-sso"
        property "sonar.organization", "akarmanov2022"
        property "sonar.host.url", "https://sonarcloud.io"
        property "sonar.java.checkstyle.reportPaths", "build/reports/checkstyle/main.xml,build/reports/checkstyle/test.xml"
    }
}

node {
    version = '23.10.0'
    npmVersion = '10.9.2'
    download = !project.hasProperty('prod')
    nodeProjectDir = file("${projectDir}/frontend")
}

tasks.register('installReact', NpmTask) {
    args = ['install']
    workingDir = file("${projectDir}/frontend")
}

tasks.register('buildReact', NpmTask) {
    args = ['run', 'build']
    workingDir = file("${projectDir}/frontend")
    dependsOn installReact
}

// Копируем ассеты
tasks.register('copyReactStatic', Copy) {
    dependsOn 'buildReact'
    from("${projectDir}/frontend/build/static")
    into("src/main/resources/static")
}

// Копируем index.html в шаблоны Thymeleaf
tasks.register('copyReactIndex', Copy) {
    dependsOn 'buildReact'
    from("${projectDir}/frontend/build/index.html")
    into("src/main/resources/templates")
}

processResources.dependsOn('copyReactStatic', 'copyReactIndex')
