server:
  port: 8082
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: development
  application:
    name: meeting-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:project-place}
    username: ${DB_USERNAME:project-place}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/project-place}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 10
      initialization-fail-timeout: 1
      leak-detection-threshold: 0
      pool-name: "HikariPool-trackme-meeting-service"
      register-mbeans: true
      schema: ${MEETING_DB_SCHEMA:meeting_service}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  liquibase:
    enabled: true
    default-schema: ${MEETING_DB_SCHEMA:meeting_service}
    liquibase-schema: ${MEETING_DB_SCHEMA:meeting_service}
    change-log: classpath:db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SSO_URI:http://localhost:9000}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      missing-topics-fatal: false
      concurrency: 3
      ack-mode: record
      poll-timeout: 3000
      auto-startup: true

error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    enabled: false
app:
  acl:
    sid-identity-query: "select currval(pg_get_serial_sequence('acl_sid', 'id'))"
    class-identity-query: "select currval(pg_get_serial_sequence('acl_class', 'id'))"
  api-url: ${BACKEND_URI:http://127.0.0.1:8081}/meeting
  app-url: ${FRONTEND_URI:http://127.0.0.1:3000}
---
spring:
  config:
    activate:
      on-profile: development
  liquibase:
    contexts: dev prod
logging:
  level:
    org.springframework.security: trace

---
spring:
  config:
    activate:
      on-profile: docker-local
  liquibase:
    contexts: dev prod
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://trackme-sso:9000
logging:
  level:
    org.springframework.security: trace
app:
  api-url: ${BACKEND_URI:http://localhost}/meeting/

---
spring:
  config:
    activate:
      on-profile: production
  liquibase:
    contexts: prod
logging:
  level:
    root: info